---
kind: pipeline
type: docker
name: default

steps:
- name: build builder
  image: plugins/docker
  settings:
    repo: tinhead/rpi0w-image-builder
    username:
      from_secret: Hub_user
    password:
      from_secret: Hub_pass