version: 2
jobs:
  build:
    docker:
      - image: tinhead/rpi0w-image-builder

    steps:
      - checkout
      - run: 
          name: build the sd image
          command: cd /usr/local/buildroot-2019.02.6/; make FORCE_UNSAFE_CONFIGURE=1 BR2_EXTERNAL=/root/project 