version: 2
jobs:
  build:
    docker:
      - image: debian:stretch

    steps:
      - checkout
      - run: ls -al
      - run: 
          name: Get Buildroot LTS
          command: curl https://buildroot.org/downloads/buildroot-2019.02.6.tar.bz2 
      - run: ls -al 